#import "ViewController.h"
#import <React/RCTRootView.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTEventEmitter.h>

#import <UIKit/UIKit.h>
#import <WebKit/WKWebView.h>
#import <WebKit/WKWebViewConfiguration.h>

@interface ViewController ()<WKUIDelegate>
@property (nonatomic, strong) WKWebView *webView;
@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    self.view.backgroundColor = [UIColor redColor];
//    [self initRCTRootView];
//    [self initReactView];
    [self initWKWebView];
}

- (void)initRCTRootView
{
    NSURL *jsCodeLocation;
    // jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.bundle?platform=ios"]; 
    //Manually concatenate JScodeLocation for the development environment 
    //jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"]; 
    //read the static JS bundle named main from the package after release, 
    jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"webFrontend/src/index" fallbackResource:nil]; // Generated by RCTBundleUrlProvider for use in the development environment
    //The "App1" name must be the same as the name registered in index.js
    RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation moduleName:@"App" initialProperties:nil
                                                     launchOptions:nil];
    self.view = rootView;
}

- (void)initReactView
{
    NSLog(@"High Score Button Pressed");
    NSURL *jsCodeLocation = [NSURL URLWithString:@"http://www.cookbokubc.ml/"];
    RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                        moduleName:@"App"
                                                 initialProperties:nil
                                                     launchOptions:nil];
    self.view = rootView;
}

- (void)initWKWebView
{
    NSURL *url = [[NSURL alloc]initWithString:@"http://www.cookbokubc.ml/"];
    NSURLRequest *request = [[NSURLRequest alloc] initWithURL:url];
    [self.webView loadRequest:request];
}

- (WKWebView *)webView {
    if (_webView) {
        return _webView;
    }
    WKWebViewConfiguration *webViewConfig = [[WKWebViewConfiguration alloc] init];
    _webView = [[WKWebView alloc] initWithFrame:CGRectMake(0,0,self.view.bounds.size.width,self.view.bounds.size.height)
                                  configuration:webViewConfig];
    _webView.UIDelegate = self;
    [self.view addSubview:_webView];
    return _webView;
}

@end
