version: '3.3'

services:
  flask:
    image: cookbookimage
    ports:
      - "8080:8080"
    networks:
      - appnet
    deploy:
      mode: replicated
      replicas: 1
networks:
  appnet:
    driver: overlay
